@startuml Renewal
header Page Header
footer Page %page% of %lastpage%

title Renewing a Uris Policy - Option 3

Participant "PolicyRenewalProcessor" as prp
Participant "Policy Api" as policyService
Database "Policy Database" as policyDb
Participant "Payments Api" as paymentService
Database "Payment Database" as paymentDatabase
Participant "GoCardless" as goCardless

autonumber

loop For each policy to be renewed

    prp -> policyService : Send Renewal \n with Price
activate prp

    
    activate policyService
policyService -> paymentService
    activate paymentService
        paymentService -> goCardless : Create Billing Request
        activate goCardless
        goCardless --> paymentService : (OK)
        deactivate goCardless
        paymentService -> paymentDatabase : Create Mandate
        activate paymentDatabase
        paymentDatabase --> paymentService: Mandate Created (OK)
        deactivate paymentDatabase
        paymentService -> goCardless : Create Customer
        activate goCardless
        goCardless --> paymentService : (OK)
        deactivate goCardless
        paymentService -> goCardless : Create Bank Details
        activate goCardless
        goCardless --> paymentService : (OK)
        deactivate goCardless
        paymentService -> goCardless : Confirm Payer Details
        activate goCardless
        goCardless --> paymentService : (OK)
        deactivate goCardless
        paymentService -> goCardless : Fulfill Billing Request
        activate goCardless
        goCardless --> paymentService : (OK)
        deactivate goCardless
        paymentService -> paymentDatabase : Update Mandate
        activate paymentDatabase
        paymentDatabase --> paymentService: Mandate Updated (OK)
        deactivate paymentDatabase

        '' Publish Mandate Success Message Here

        paymentService -> paymentDatabase : Get Mandate
        activate paymentDatabase
        paymentDatabase --> paymentService: Return Mandate (OK)
        deactivate paymentDatabase

        paymentService -> paymentService : Adjust PaymentChargeDate
        paymentService -> goCardless : Request payment
        activate goCardless
        goCardless --> paymentService : Payment requested (OK)
        deactivate goCardless
        paymentService -> paymentDatabase : Create Payment
        activate paymentDatabase
        paymentDatabase --> paymentService : Payment Created (OK)
        deactivate paymentDatabase
        paymentService --> policyService : Mandate Setup And Payment Requested (OK)
    deactivate paymentService

        policyService -> policyDb : Create Renewal
        activate policyDb
            policyDb --> policyService : Renewal Created (OK)
        deactivate policyDb
        policyService --> prp : Renewal Created (OK)
    deactivate policyService
deactivate prp
end

@enduml