@startuml x
header Page Header
footer Page %page% of %lastpage%

title Renewing a Policy with an invalid Direct Debit Mandate

Actor "Customer Advisor" as customerAdvisor
Participant "Policy UI" as policyAdministrationUI
Participant "Policy Api" as policyApi
Database "Policy Database Database" as policyDatabase
Participant "Payments Api" as paymentService
Database "Payment Database" as paymentDatabase
Participant "GoCardless" as goCardless

autonumber 1.0

'Include Publish to outbox (database & queue)
'https://uinsure.atlassian.net/browse/PL-694
group Setup New Payment Method
customerAdvisor -> policyAdministrationUI : Provide bank details for Direct Debit
activate customerAdvisor
    activate policyAdministrationUI
    policyAdministrationUI -> paymentService : Request Mandate Setup
        activate paymentService
            paymentService -> goCardless : Create Billing Request
            activate goCardless
            goCardless --> paymentService : (OK)
            deactivate goCardless
            paymentService -> paymentDatabase : Create Mandate
            activate paymentDatabase
            paymentDatabase --> paymentService: Mandate Created (OK)
            deactivate paymentDatabase
            paymentService -> goCardless : Create Customer
            activate goCardless
            goCardless --> paymentService : (OK)
            deactivate goCardless
            paymentService -> goCardless : Create Bank Details
            activate goCardless
            goCardless --> paymentService : (OK)
            deactivate goCardless
            paymentService -> goCardless : Confirm Payer Details
            activate goCardless
            goCardless --> paymentService : (OK)
            deactivate goCardless
            paymentService -> goCardless : Fulfill Billing Request
            activate goCardless
            goCardless --> paymentService : (OK)
            deactivate goCardless
            paymentService -> paymentDatabase : Update Mandate
            activate paymentDatabase
            paymentDatabase --> paymentService: Mandate Updated (OK)
            deactivate paymentDatabase
            paymentService --> policyAdministrationUI : Mandate Setup(OK)
        deactivate paymentService
        policyAdministrationUI --> customerAdvisor : Mandate Setup (OK)
    deactivate policyAdministrationUI
deactivate customerAdvisor
end
autonumber 2.0
group Request Renewal Payment

customerAdvisor -> policyAdministrationUI : Resubmit Renewal Payment
activate customerAdvisor
    activate policyAdministrationUI
        policyAdministrationUI -> policyApi : Request Policy Renewal \n Payment
        activate policyApi
            policyApi -> policyDatabase : Get Renewal Transaction
            activate policyDatabase
            policyDatabase --> policyApi : (OK)
            deactivate policyDatabase
            policyApi -> paymentService : Send Payment Request to provider
            activate paymentService
                paymentService -> goCardless : Request payment
                activate goCardless
                goCardless --> paymentService : Payment requested (OK)
                deactivate goCardless
                paymentService -> paymentDatabase : Create Payment
                activate paymentDatabase
                paymentDatabase --> paymentService : Payment Created (OK)
                deactivate paymentDatabase
                paymentService --> policyApi : (OK)
            deactivate paymentService
            policyApi -> policyDatabase : Create Payment
            activate policyDatabase
            policyDatabase --> policyApi : (OK)
            deactivate policyDatabase
            policyApi --> policyAdministrationUI : Payment Requested & \n Policy Updated (OK)
        deactivate policyApi
        policyAdministrationUI --> customerAdvisor : Renewal Payment Submitted (OK)
    deactivate policyAdministrationUI
deactivate customerAdvisor

end


@enduml